# Generated by Django 6.0.6 on 2026-07-08 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='image',
            name='catagory',
        ),
        migrations.AddField(
            model_name='image',
            name='catagory',
            field=models.ManyToManyField(to='base.catagories'),
        ),
    ]
