# Generated by Django 6.0.6 on 2026-07-08 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_catagories_remove_image_catagory_image_catagory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='catagory',
            field=models.ManyToManyField(related_name='images', to='base.catagories'),
        ),
        migrations.AlterField(
            model_name='image',
            name='upload_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
